# Generated by Django 3.2 on 2023-10-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('contact', models.BigIntegerField()),
                ('customer_us_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=200)),
                ('contact', models.BigIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('average_rating', models.IntegerField(default=3)),
                ('register_date', models.DateTimeField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_details')),
            ],
        ),
        migrations.CreateModel(
            name='item_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(default='')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_customer')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_details')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=500)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_details')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_table')),
            ],
        ),
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.item_category')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_details')),
            ],
        ),
        migrations.AddField(
            model_name='hotel_customer',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_hotel.hotel_details'),
        ),
    ]
